#! /bin/bash

DISTROOT=dist

./make

# Construct Image
mkdir -p dist/dmg/dist
cp -Rf Examples Icon.png License.txt README.md dist/dmg
cp -Rf dist/mac dist/ios dist/dmg/dist
rm -Rf $DISTROOT/Examples/*/*.xcodeproj/project.xcworkspace
rm -Rf $DISTROOT/Examples/*/*.xcodeproj/xcuserdata

# create disk image
rm -f $DISTROOT/AsyncNetwork.dmg
hdiutil create -srcfolder dist/dmg -fs HFS+ -volname AsyncNetwork $DISTROOT/AsyncNetwork.dmg
